export const SET_USER = 'SET_USER'
export const SET_USER_ERROR = 'SET_USER_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'
export const VALIDATE_SUCCESS = 'VALIDATE_SUCCESS'
export const VALIDATE_ERROR = 'VALIDATE_ERROR'
export const CREATE_POST = 'CREATE_POST'
export const SET_POSTS = 'SET_POSTS'
export const SET_CURRENT_POST = 'SET_CURRENT_POST'




